# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if PR into 'main' is from 'dev' branch
        if: github.event.pull_request.base.ref == 'main'
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Error: Pull requests to main must originate from the dev branch."
            exit 1
          fi
        shell: bash

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check prettier compliance
        run: npm run prettier --if-present

      - name: Check stylelint compliance
        run: npm run stylelint --if-present

      - name: Check lint compliance
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: TypeScript Type Check
        run: npm run type-check --if-present

      - name: Run unit tests
        run: npm test --if-present
